var nameSurname = prompt("Введите своё имя")
console.log("nameSurname")
var planetName = ("Земля")
console.log("planetName")
var doYouLive = confirm("Живешь ли ты на планете " + planetName + ", " + nameSurname + "?")
console.log("doYouLive")